services:
  - type: web
    name: yt-buzz
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: COOKIE_DATA
        sync: false
    healthCheckPath: /
    autoDeploy: true
