// YT Buzz Cookie Helper — Background Service Worker

const SERVER_URL = "https://yt-buzz.onrender.com";

/**
 * Convert Chrome cookies to Netscape format (compatible with yt-dlp)
 */
function cookiesToNetscape(cookies) {
  const lines = ["# Netscape HTTP Cookie File", "# This file is generated by YT Buzz Cookie Helper. Do not edit.", ""];
  for (const cookie of cookies) {
    const domain = cookie.domain;
    const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
    const path = cookie.path || "/";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = cookie.expirationDate ? Math.floor(cookie.expirationDate) : "0";
    const name = cookie.name;
    const value = cookie.value;
    lines.push(`${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expires}\t${name}\t${value}`);
  }
  return lines.join("\n");
}

/**
 * Extract YouTube cookies and send to YT Buzz server
 */
async function extractAndSendCookies() {
  try {
    // Get all YouTube cookies
    const cookies = await chrome.cookies.getAll({ domain: ".youtube.com" });

    if (cookies.length === 0) {
      return { success: false, message: "No YouTube cookies found. Make sure you are logged into YouTube." };
    }

    // Check for essential auth cookies
    const essentialCookies = ["SID", "HSID", "SSID", "APISID", "SAPISID", "__Secure-1PSID", "__Secure-3PSID"];
    const foundEssential = cookies.filter(c => essentialCookies.includes(c.name));

    if (foundEssential.length < 3) {
      return { success: false, message: `Only found ${foundEssential.length}/${essentialCookies.length} essential auth cookies. Please make sure you are fully logged into YouTube.` };
    }

    // Convert to Netscape format
    const netscapeText = cookiesToNetscape(cookies);

    // Send to server
    const response = await fetch(`${SERVER_URL}/api/extension-cookies`, {
      method: "POST",
      headers: { "Content-Type": "text/plain" },
      body: netscapeText,
    });

    const data = await response.json();

    if (response.ok) {
      // Save last sync time as timestamp for cooldown logic
      const now = Date.now();
      await chrome.storage.local.set({ lastSync: now, cookieCount: cookies.length });

      return { success: true, message: data.message || "Cookies synced successfully!", cookieCount: cookies.length, lastSync: new Date(now).toISOString() };
    } else {
      return { success: false, message: data.detail || "Server rejected the cookies." };
    }
  } catch (error) {
    return { success: false, message: `Error: ${error.message}` };
  }
}

/**
 * Auto-sync cookies when user navigates to YouTube
 * Includes 5-minute cooldown to avoid spamming the server
 */
chrome.tabs.onUpdated.addListener(async (tabId, changeInfo, tab) => {
  if (changeInfo.status === "complete" && tab.url && tab.url.includes("youtube.com")) {
    const { autoSync, lastSync } = await chrome.storage.local.get(["autoSync", "lastSync"]);
    if (autoSync) {
      // Cooldown: don't re-sync within 5 minutes
      const fiveMinutes = 5 * 60 * 1000;
      const now = Date.now();
      if (lastSync && (now - lastSync) < fiveMinutes) {
        return; // Too soon, skip sync
      }
      await extractAndSendCookies();
    }
  }
});

/**
 * Handle messages from popup
 */
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
  if (request.action === "syncCookies") {
    extractAndSendCookies().then(sendResponse);
    return true; // Keep channel open for async response
  }
  if (request.action === "getStatus") {
    chrome.storage.local.get(["lastSync", "cookieCount", "autoSync"], (data) => {
      sendResponse(data);
    });
    return true;
  }
  if (request.action === "setAutoSync") {
    chrome.storage.local.set({ autoSync: request.value });
    sendResponse({ success: true });
    return true;
  }
});
